---
- name: prerequisites | JBoss EAP 7.3 Repository
  community.general.rhsm_repository:
    name:
      - jb-eap-7.3-for-rhel-8-x86_64-rpms
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
